/**
 * @fileoverview gRPC-Web generated client stub for location
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.30.2
// source: location.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as location_pb from './location_pb'; // proto import: "location.proto"


export class LocationServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSendLocation = new grpcWeb.MethodDescriptor(
    '/location.LocationService/SendLocation',
    grpcWeb.MethodType.UNARY,
    location_pb.LocationRequest,
    location_pb.Empty,
    (request: location_pb.LocationRequest) => {
      return request.serializeBinary();
    },
    location_pb.Empty.deserializeBinary
  );

  sendLocation(
    request: location_pb.LocationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<location_pb.Empty>;

  sendLocation(
    request: location_pb.LocationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: location_pb.Empty) => void): grpcWeb.ClientReadableStream<location_pb.Empty>;

  sendLocation(
    request: location_pb.LocationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: location_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/location.LocationService/SendLocation',
        request,
        metadata || {},
        this.methodDescriptorSendLocation,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/location.LocationService/SendLocation',
    request,
    metadata || {},
    this.methodDescriptorSendLocation);
  }

  methodDescriptorSubscribeLocations = new grpcWeb.MethodDescriptor(
    '/location.LocationService/SubscribeLocations',
    grpcWeb.MethodType.SERVER_STREAMING,
    location_pb.UserIdRequest,
    location_pb.LocationResponse,
    (request: location_pb.UserIdRequest) => {
      return request.serializeBinary();
    },
    location_pb.LocationResponse.deserializeBinary
  );

  subscribeLocations(
    request: location_pb.UserIdRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<location_pb.LocationResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/location.LocationService/SubscribeLocations',
      request,
      metadata || {},
      this.methodDescriptorSubscribeLocations);
  }

}

