services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - '2181:2181'
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper:2888:3888
      - ZOO_4LW_COMMANDS_WHITELIST=stat

volumes:
  zookeeper_data:
    driver: local
